language: php

matrix:
  fast_finish: true
  include:
    - php:
        - 7.1
        - 7.2
        - 7.3
        - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpstan analyse -l ${PHPSTAN_LEVEL:-1} --no-progress src/
  - vendor/bin/phpcs --standard=PSR2 -n src/
