# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: daccbr/ahsay-php

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install
          - vendor/bin/phpstan analyse -l ${PHPSTAN_LEVEL:-1} --no-progress src/
          - vendor/bin/phpcs --standard=PSR2 -n src/
          - vendor/bin/phpunit --coverage-text

  branches:
    '*':
      - step:
          caches:
            - composer
          script:
            - composer install
            - if CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "HEAD~..HEAD" | grep .php) ; then vendor/bin/phpstan analyse -l ${PHPSTAN_LEVEL:-1} --no-progress ${CHANGED_FILES}; fi
            - if CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "HEAD~..HEAD" | grep .php) ; then vendor/bin/phpcs --standard=PSR2 -n ${CHANGED_FILES}; fi
            - vendor/bin/phpunit --coverage-text

  pull-requests:
    '**':
      - step:
          caches:
            - composer
          script:
            - composer install
            - if CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH | grep .php) ; then vendor/bin/phpstan analyse -l ${PHPSTAN_LEVEL:-1} --no-progress ${CHANGED_FILES}; fi
            - if CHANGED_FILES=$(git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH | grep .php) ; then vendor/bin/phpcs --standard=PSR2 -n ${CHANGED_FILES}; fi
            - vendor/bin/phpunit --coverage-text
